### ISSUE TITLE
Developer resources status

### ISSUE THREAD

**Issue by muka** [raptorbox/raptor#19]
## Documentation
- [x] #12 Generate Swagger documentation for Raptor API
- [x] #11 Generate Swagger documentation for security API
- [x] #20 Update and migrate previous documentation to Jekill / github.io 
## SDK
- [ ] #4   Java client SDK
- [x] #15  Javascript client SDK
## Deployment & Testing
- [x] #18 Docker based deployment
- [x] #17 Docker compose support
- [ ] #16 Kubernetes support
